---
apiVersion: v1
kind: Pod
metadata:
    name: fortune-pod
    # namespace: fortune-ns
    labels:
        app: fortune
spec:
    containers:
    - name: fortune-container
      image: chukmunnlee/fortune:v1
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 3000
