# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#namespace-v1-core
---
apiVersion: v1
kind: Namespace
metadata:
    name: fortune-ns
    labels:
        app: fortune
        version: v1
        cost-center: engineering

---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
    name: fortune-deploy
    namespace: fortune-ns
    labels:
        app: fortune

spec:
    replicas: 3
    selector:
        matchLabels:
            app: fortune-pod
    template:
        metadata:
            name: fortune-pod
            labels:
                app: fortune-pod
        spec:
            containers:
            - name: fortune-container
              image: ystrapidz/fortune:v1
              imagePullPolicy: IfNotPresent
              ports:
              - name: for-port
                containerPort: 3000

---
# Service
apiVersion: v1
kind: Service
metadata:
    name: fortune-svc
    namespace: fortune-ns
    labels:
        app: fortune
spec:
    type: ClusterIP
    selector:
        app: fortune-pod
    ports:
    - name: for-svc-port
      port: 3000
      targetPort: for-port

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: fortune-ing
    labels:
        app: fortune
spec:
    rules:
    - host: fortune.167.172.5.53.nip.io
      http:
          paths:
          - path: /
            backend:
                serviceName: fortune-svc
                servicePort: for-svc-port
