---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nwdb-pvc
    labels:
        app: northwind
    annotations:
        volume.beta.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com  # kubectl get sc
spec:
    accessModes:
    - ReadWriteOnce
    storageClassName: do-block-storage      # kubectl get sc
    resources:
        requests:
            storage: 1Gi  # Gi = 1024MB,  G = 1000MB
